# Generated by Django 5.1.4 on 2025-08-25 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.TimeField(auto_now_add=datetime.datetime(2025, 8, 25, 5, 23, 19, 359765, tzinfo=datetime.timezone.utc)),
        ),
    ]
