# Generated by Django 5.1.4 on 2025-11-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_username_account_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='+265********', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='userID',
            field=models.CharField(default='-----', max_length=15),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Unknown', max_length=15)),
                ('VIN', models.CharField(default='------', max_length=15)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('color', models.CharField(default='Unavailable', max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
