# Generated by Django 5.1.4 on 2025-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plate',
            field=models.CharField(default='MLW 000', max_length=10),
        ),
    ]
