# Generated by Django 5.1.4 on 2025-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_client_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plate',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='MLW 000', max_length=10),
        ),
    ]
