# Generated by Django 5.1.4 on 2025-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_client_plate_vehicle_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userID',
            field=models.CharField(default='00000', max_length=15),
        ),
    ]
