# Generated by Django 5.1.4 on 2025-11-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_client_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='is_active',
        ),
    ]
