# Generated by Django 5.1.4 on 2025-12-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_rename_status_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.client'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='MLW 000', max_length=10, unique=True),
        ),
    ]
