# Generated by Django 5.1.4 on 2025-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='email',
            field=models.EmailField(default='noemail@gmail.com', max_length=254, unique=True),
        ),
    ]
