# Generated by Django 5.1.4 on 2025-12-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sendmessage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='email',
            field=models.EmailField(default='noemail@gmail.com', max_length=254),
        ),
    ]
